import { useEffect, useState } from 'react'
import { AlertTriangle, Plus } from 'lucide-react'
import { api } from '../lib/api'
import { money, date } from '../lib/format'
import { PageHeader } from '../components/PageHeader'
import { DataTable } from '../components/DataTable'
import { StatusBadge } from '../components/StatusBadge'
import '../costs.css'
import { useAuth } from '../components/AuthContext'
import { can } from '../lib/permissions'

export function CostsPage() {
  const {user}=useAuth(); const canWrite=can(user?.role,'cost:w'); const canApprove=can(user?.role,'cost:approve')||['DIRECTOR','SYSTEM_ADMIN'].includes(user?.role||''); const canPay=can(user?.role,'finance:w')
  const [budgets,setBudgets]=useState<any[]>([]); const [expenses,setExpenses]=useState<any[]>([]); const [show,setShow]=useState(false); const [paying,setPaying]=useState<any>(null); const [error,setError]=useState('')
  const load=()=>Promise.all([api.get('/costs/budgets'),api.get('/costs/expenses')]).then(([b,e])=>{setBudgets(b.data);setExpenses(e.data)})
  useEffect(()=>{load()},[])
  const fail=(e:any)=>setError(e?.response?.data?.detail||'Không thể xử lý yêu cầu')
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();try{const f=new FormData(e.currentTarget);const payload:any=Object.fromEntries(f);payload.amount=Number(payload.amount);payload.budget_id=payload.budget_id?Number(payload.budget_id):null;await api.post('/costs/expenses',payload);setShow(false);load()}catch(e){fail(e)}}
  const action=async(id:number,type:string)=>{try{await api.post(`/costs/expenses/${id}/${type}`,type==='approve'||type==='reject'?{}:undefined);load()}catch(e){fail(e)}}
  const pay=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();try{const x:any=Object.fromEntries(new FormData(e.currentTarget));x.amount=Number(x.amount);await api.post(`/costs/expenses/${paying.id}/pay`,x);setPaying(null);load()}catch(e){fail(e)}}
  return <><PageHeader title="Quản lý chi phí" description="Kiểm soát ngân sách, chi phí thực tế, đề nghị thanh toán và phê duyệt." actions={canWrite&&<button className="primary-btn small" onClick={()=>setShow(true)}><Plus size={17}/> Tạo chi phí</button>}/>
    {error&&<div className="error-panel"><AlertTriangle size={16}/>{error}</div>}
    <div className="budget-grid">{budgets.map(b=>{const used=Number(b.spent_amount)+Number(b.committed_amount||0);return <div className="budget-card" key={b.id}><div><span>{b.department}</span><strong>{b.name}</strong></div><div className="budget-values"><b>{money(b.spent_amount)}</b><span>/ {money(b.amount)}</span></div><div className="progress"><i style={{width:`${Math.min(100,used/Number(b.amount)*100)}%`}}/></div><small>Đã cam kết {money(b.committed_amount||0)} · Còn {money(Number(b.amount)-used)} · {b.period}</small></div>})}</div>
    <section className="panel"><div className="panel-title"><div><h3>Danh sách chi phí</h3><p>Chi phí chờ duyệt, đã duyệt và từ chối</p></div></div><DataTable rows={expenses} columns={[
      {key:'code',label:'Mã'}, {key:'description',label:'Nội dung'}, {key:'department',label:'Phòng ban'}, {key:'category',label:'Nhóm'}, {key:'expense_date',label:'Ngày',render:(r:any)=>date(r.expense_date)}, {key:'amount',label:'Số tiền',render:(r:any)=>money(r.amount)}, {key:'status',label:'Trạng thái',render:(r:any)=><StatusBadge value={r.status}/>},
      {key:'action',label:'Thao tác',render:(r:any)=><div className="row-actions">{canWrite&&['DRAFT','REJECTED'].includes(r.status)&&<button className="table-btn" onClick={()=>action(r.id,'submit')}>Gửi duyệt</button>}{canApprove&&['SUBMITTED','OVER_BUDGET'].includes(r.status)&&<><button className="table-btn" onClick={()=>action(r.id,'approve')}>Duyệt</button><button className="table-btn" onClick={()=>action(r.id,'reject')}>Từ chối</button></>}{canPay&&r.status==='APPROVED'&&<button className="table-btn" onClick={()=>setPaying(r)}>Thanh toán</button>}</div>}
    ]}/></section>
    {show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><h3>Tạo đề nghị chi phí</h3><div className="form-grid"><label>Mã chi phí<input name="code" required placeholder="CP-00085"/></label><label>Số tiền<input name="amount" required type="number" min="1"/></label><label className="full">Nội dung<input name="description" required/></label><label>Phòng ban<select name="department"><option>Kinh doanh</option><option>Kỹ thuật</option><option>Kế toán</option><option>Kho</option><option>HCVP</option></select></label><label>Ngân sách<select name="budget_id" defaultValue=""><option value="">Tự động theo phòng ban</option>{budgets.filter(b=>b.status==='APPROVED').map(b=><option key={b.id} value={b.id}>{b.code} — còn {money(Number(b.amount)-Number(b.spent_amount)-Number(b.committed_amount||0))}</option>)}</select></label><label>Nhóm chi phí<select name="category"><option>Vật tư</option><option>Vận chuyển</option><option>Marketing</option><option>Vận hành</option><option>Công tác</option></select></label><label>Ngày chi<input name="expense_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="full">Chứng từ tham chiếu<input name="attachment_refs" placeholder="Hóa đơn/đề nghị/đường dẫn hồ sơ"/></label></div><div className="modal-actions"><button type="button" className="ghost-btn" onClick={()=>setShow(false)}>Hủy</button><button className="primary-btn">Lưu đề nghị chi</button></div></form></div>}
    {paying&&<div className="modal-backdrop" onMouseDown={()=>setPaying(null)}><form className="modal" onSubmit={pay} onMouseDown={e=>e.stopPropagation()}><h3>Thanh toán {paying.code}</h3><div className="form-grid"><label>Ngày chi<input name="paid_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Số tiền<input name="amount" type="number" required readOnly defaultValue={paying.amount}/></label><label>Phương thức<select name="method"><option value="BANK_TRANSFER">Chuyển khoản</option><option value="CASH">Tiền mặt</option></select></label><label>Mã giao dịch/UNC<input name="transaction_ref"/></label></div><div className="modal-actions"><button type="button" className="ghost-btn" onClick={()=>setPaying(null)}>Hủy</button><button className="primary-btn">Ghi nhận actual cost</button></div></form></div>}
  </>
}
