import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import { PageHeader } from '../components/PageHeader'
import { DataTable } from '../components/DataTable'

const roleName: Record<string,string>={SYSTEM_ADMIN:'Quản trị hệ thống',DIRECTOR:'Ban giám đốc',DIRECTOR_ASSISTANT:'Trợ lý BGĐ',MARKETING:'Marketing',SALES:'Kinh doanh',SALES_ADMIN:'Sales Admin',TECH_SOLUTION:'Kỹ thuật giải pháp',TECH_FIELD:'Kỹ thuật hiện trường',ACCOUNTING:'Kế toán',PURCHASING:'Mua hàng',WAREHOUSE:'Kho',CASHIER:'Quỹ',HCVP:'Hành chính văn phòng',HR:'Nhân sự',CUSTOMER_SERVICE:'Chăm sóc khách hàng'}
export function OrganizationPage(){const[users,setUsers]=useState<any[]>([]);const[roles,setRoles]=useState<any[]>([]);const[error,setError]=useState('');useEffect(()=>{Promise.all([api.get('/admin/users'),api.get('/admin/roles')]).then(([u,r])=>{setUsers(u.data);setRoles(r.data)}).catch(e=>setError(e.response?.data?.detail||'Không có quyền xem danh sách nhân sự'))},[])
return <><PageHeader title="Tổ chức & phân quyền" description="Mô hình quyền dựa trên sơ đồ tổ chức và nhiệm vụ từng phòng ban."/>
<div className="org-chart"><div className="org-node director">Ban giám đốc</div><div className="org-line"/><div className="org-level">{['Marketing','Kinh doanh','Kỹ thuật','Kế toán','Kho · Quỹ · HCVP'].map(x=><div className="org-node" key={x}>{x}</div>)}</div><div className="org-sub">Kinh doanh: Telesales · Sales dự án · Sales Admin &nbsp; | &nbsp; Kỹ thuật: Giải pháp · Hiện trường &nbsp; | &nbsp; Kế toán: Tổng hợp · Mua hàng</div></div>
{error?<div className="error-panel">{error}</div>:<section className="panel"><div className="panel-title"><div><h3>Người dùng hệ thống</h3><p>Tài khoản demo theo phòng ban</p></div></div><DataTable rows={users} columns={[{key:'full_name',label:'Họ tên'},{key:'email',label:'Email'},{key:'department',label:'Phòng ban'},{key:'role',label:'Vai trò',render:(r:any)=>roleName[r.role]||r.role},{key:'is_active',label:'Trạng thái',render:(r:any)=><span className="badge badge-active">{r.is_active?'Hoạt động':'Khóa'}</span>} ]}/></section>}
<section className="panel"><div className="panel-title"><div><h3>Ma trận quyền</h3><p>{roles.length} vai trò đã cấu hình theo nguyên tắc tối thiểu cần thiết</p></div></div><div className="role-grid">{roles.map(r=><article key={r.role}><h4>{roleName[r.role]||r.role}</h4><p>{r.permissions.length} quyền</p><div>{r.permissions.map((p:string)=><span key={p}>{p}</span>)}</div></article>)}</div></section></>}
