import { useEffect, useState } from 'react'
import { Plus } from 'lucide-react'
import { api } from '../lib/api'
import { date } from '../lib/format'
import { PageHeader } from '../components/PageHeader'
import { DataTable } from '../components/DataTable'
import { StatusBadge } from '../components/StatusBadge'

export function SupportPage(){const[rows,setRows]=useState<any[]>([]);const[customers,setCustomers]=useState<any[]>([]);const[show,setShow]=useState(false);const load=()=>Promise.all([api.get('/support/tickets'),api.get('/sales/customers')]).then(([t,c])=>{setRows(t.data);setCustomers(c.data)});useEffect(()=>{load()},[]);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api.post('/support/tickets',{code:f.get('code'),customer_id:Number(f.get('customer_id')),subject:f.get('subject'),priority:f.get('priority')});setShow(false);load()}
return <><PageHeader title="CSKH & bảo hành" description="Tiếp nhận yêu cầu sau bán, điều phối kỹ thuật và theo dõi SLA phản hồi." actions={<button className="primary-btn small" onClick={()=>setShow(true)}><Plus size={17}/> Tạo yêu cầu</button>}/><section className="panel"><DataTable rows={rows} columns={[{key:'code',label:'Mã phiếu'},{key:'subject',label:'Yêu cầu'},{key:'customer_id',label:'Khách hàng',render:(r:any)=>customers.find(c=>c.id===r.customer_id)?.name||`KH #${r.customer_id}`},{key:'priority',label:'Ưu tiên',render:(r:any)=><StatusBadge value={r.priority}/>},{key:'status',label:'Trạng thái',render:(r:any)=><StatusBadge value={r.status}/>},{key:'sla_due_at',label:'Hạn SLA',render:(r:any)=>date(r.sla_due_at)}]}/></section>{show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><h3>Tạo yêu cầu CSKH</h3><div className="form-grid"><label>Mã phiếu<input name="code" required placeholder="CS-2026-073"/></label><label>Khách hàng<select name="customer_id">{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="full">Nội dung<input name="subject" required/></label><label>Ưu tiên<select name="priority"><option value="LOW">Thấp · 48 giờ</option><option value="MEDIUM">Trung bình · 24 giờ</option><option value="HIGH">Cao · 4 giờ</option><option value="CRITICAL">Khẩn cấp · 2 giờ</option></select></label></div><div className="modal-actions"><button type="button" className="ghost-btn" onClick={()=>setShow(false)}>Hủy</button><button className="primary-btn">Tạo phiếu</button></div></form></div>}</>}
