import { useEffect, useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { api } from '../../lib/api'
import { money } from '../../lib/format'
import { DataTable } from '../../components/DataTable'
import { StatusBadge } from '../../components/StatusBadge'

type Line={product_id:number|string,name:string,quantity:number,unit:string,estimated_cost:number,note?:string}
export function BomsTab(){
  const[rows,setRows]=useState<any[]>([]),[master,setMaster]=useState<any>({opportunities:[],products:[]}),[show,setShow]=useState(false),[lines,setLines]=useState<Line[]>([{product_id:'',name:'',quantity:1,unit:'Cái',estimated_cost:0}]),[error,setError]=useState('')
  const load=()=>Promise.all([api.get('/order-flow/boms'),api.get('/order-flow/master-data')]).then(([r,m])=>{setRows(r.data);setMaster(m.data)})
  useEffect(()=>{load().catch(()=>setError('Không thể tải BOM'))},[])
  const update=(i:number,p:Partial<Line>)=>setLines(lines.map((x,j)=>j===i?{...x,...p}:x))
  const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/order-flow/boms',{code:f.get('code'),opportunity_id:Number(f.get('opportunity_id')),name:f.get('name'),scope:f.get('scope'),items:lines.map(x=>({...x,product_id:Number(x.product_id)}))});setShow(false);setLines([{product_id:'',name:'',quantity:1,unit:'Cái',estimated_cost:0}]);load()}catch(e:any){setError(e.response?.data?.detail||'Không thể lưu BOM')}}
  return <>{error&&<div className="error-panel">{error}</div>}<div className="toolbar"><span>{rows.length} BOM</span><button className="primary-btn small" onClick={()=>setShow(true)}><Plus size={15}/> Tạo BOM</button></div><section className="panel"><DataTable rows={rows} columns={[{key:'code',label:'Mã BOM'},{key:'name',label:'Giải pháp'},{key:'opportunity_id',label:'Opportunity'},{key:'items',label:'Số dòng',render:(r:any)=>r.items.length},{key:'total',label:'Giá vốn',render:(r:any)=>money(r.items.reduce((s:number,x:any)=>s+x.quantity*Number(x.estimated_cost),0))},{key:'status',label:'Trạng thái',render:(r:any)=><StatusBadge value={r.status}/>} ]}/></section>{show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><form className="modal cost-modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><h3>Tạo BOM/Giải pháp</h3><div className="form-grid"><label>Mã BOM<input name="code" required/></label><label>Opportunity<select name="opportunity_id">{master.opportunities.map((o:any)=><option key={o.id} value={o.id}>{o.code} · {o.title}</option>)}</select></label><label className="full">Tên giải pháp<input name="name" required/></label><label className="full">Phạm vi/giả định/loại trừ<textarea name="scope"/></label></div>{lines.map((x,i)=><div className="form-grid" key={i} style={{gridTemplateColumns:'2fr 1fr 1fr 1fr auto'}}><label>Sản phẩm<select value={x.product_id} required onChange={e=>{const p=master.products.find((p:any)=>p.id===Number(e.target.value));update(i,{product_id:p.id,name:p.name,unit:p.unit,estimated_cost:Number(p.cost_price)})}}><option value="">Chọn hàng</option>{master.products.map((p:any)=><option value={p.id} key={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>Số lượng<input type="number" min="1" value={x.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/></label><label>ĐVT<input value={x.unit} onChange={e=>update(i,{unit:e.target.value})}/></label><label>Giá vốn<input type="number" min="0" value={x.estimated_cost} onChange={e=>update(i,{estimated_cost:Number(e.target.value)})}/></label><button type="button" className="ghost-btn" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,j)=>i!==j))}><Trash2 size={15}/></button></div>)}<button type="button" className="ghost-btn" onClick={()=>setLines([...lines,{product_id:'',name:'',quantity:1,unit:'Cái',estimated_cost:0}])}>+ Dòng BOM</button><div className="modal-actions"><button type="button" className="ghost-btn" onClick={()=>setShow(false)}>Hủy</button><button className="primary-btn">Lưu BOM</button></div></form></div>}</>
}
