import { useEffect, useState } from 'react'
import { Plus } from 'lucide-react'
import { api } from '../../lib/api'
import { DataTable } from '../../components/DataTable'
import { StatusBadge } from '../../components/StatusBadge'

export function TechnicalRequestsTab(){
  const[rows,setRows]=useState<any[]>([]),[master,setMaster]=useState<any>({opportunities:[],users:[]}),[show,setShow]=useState(false),[error,setError]=useState('')
  const load=()=>Promise.all([api.get('/production/technical-requests'),api.get('/order-flow/master-data')]).then(([r,m])=>{setRows(r.data);setMaster(m.data)})
  useEffect(()=>{load().catch(e=>setError(e.response?.data?.detail||'Không thể tải yêu cầu kỹ thuật'))},[])
  const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const x:any=Object.fromEntries(new FormData(e.currentTarget));x.opportunity_id=Number(x.opportunity_id);x.sla_hours=Number(x.sla_hours);if(x.assignee_id)x.assignee_id=Number(x.assignee_id);else delete x.assignee_id;try{await api.post('/production/technical-requests',x);setShow(false);load()}catch(e:any){setError(e.response?.data?.detail||'Không thể lưu')}}
  const act=async(r:any,action:string)=>{const note=['COMPLETE','REQUEST_INFO'].includes(action)?prompt(action==='COMPLETE'?'Kết quả hoàn thành':'Thông tin cần bổ sung')||'':undefined;try{await api.post(`/production/technical-requests/${r.id}/action`,{action,note,assignee_id:r.assignee_id});load()}catch(e:any){setError(e.response?.data?.detail||'Không thể chuyển trạng thái')}}
  return <>{error&&<div className="error-panel">{error}</div>}<div className="toolbar"><span>{rows.length} yêu cầu</span><button className="primary-btn small" onClick={()=>setShow(true)}><Plus size={15}/> Tạo yêu cầu</button></div><section className="panel"><DataTable rows={rows} columns={[
    {key:'code',label:'Mã'},{key:'request_type',label:'Loại'},{key:'scope',label:'Phạm vi'},{key:'priority',label:'Ưu tiên',render:(r:any)=><StatusBadge value={r.priority}/>},{key:'sla_due_at',label:'SLA',render:(r:any)=>new Date(r.sla_due_at).toLocaleString('vi-VN')},{key:'status',label:'Trạng thái',render:(r:any)=><StatusBadge value={r.status}/>},{key:'action',label:'Thao tác',render:(r:any)=><div className="row-actions">{r.status==='ASSIGNED'&&<button className="table-btn" onClick={()=>act(r,'ACCEPT')}>Tiếp nhận</button>}{r.status==='IN_PROGRESS'&&<><button className="table-btn" onClick={()=>act(r,'REQUEST_INFO')}>Yêu cầu bổ sung</button><button className="table-btn" onClick={()=>act(r,'COMPLETE')}>Hoàn thành</button></>}{r.status==='NEED_INFO'&&<button className="table-btn" onClick={()=>act(r,'RESUME')}>Tiếp tục</button>}</div>}
  ]}/></section>{show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><form className="modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><h3>Tạo yêu cầu kỹ thuật</h3><div className="form-grid"><label>Mã yêu cầu<input name="code" required/></label><label>Opportunity<select name="opportunity_id" required>{master.opportunities.map((o:any)=><option key={o.id} value={o.id}>{o.code} · {o.title}</option>)}</select></label><label>Loại<select name="request_type"><option value="SURVEY">Khảo sát</option><option value="SOLUTION">Giải pháp</option><option value="PRE_SALE">Pre-sale</option></select></label><label>Ưu tiên<select name="priority"><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><label className="full">Phạm vi<textarea name="scope" required/></label><label>Địa điểm<input name="site_address"/></label><label>SLA giờ<input name="sla_hours" type="number" min="1" defaultValue="24"/></label><label>Kỹ thuật phụ trách<select name="assignee_id"><option value="">Chưa phân công</option>{master.users.map((u:any)=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="ghost-btn" onClick={()=>setShow(false)}>Hủy</button><button className="primary-btn">Lưu</button></div></form></div>}</>
}
